const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const path = require('node:path');
const { test } = require('node:test');
const { normalize, inspectPullRequest, run } = require('./attribution.cjs');
const branches = require('./fixtures/branches.json');

const root = path.resolve(__dirname, '../..');
const identity = { name: 'BichengWang', email: 'bichengwang17@gmail.com' };
const cleanCommit = {
  sha: 'a'.repeat(40), message: 'Add workflow checks', author: identity, committer: identity,
};
const cleanPR = {
  actor: 'BichengWang', branch: 'agents/eval-harness', title: 'Add workflow checks',
  body: 'Run the offline checks on pull requests.', commits: [cleanCommit],
};

function git(...args) {
  return execFileSync('git', args, { cwd: root, encoding: 'utf8' });
}

test('last 30 commits pass message and identity rules', t => {
  const fields = git('log', '-30', '--format=%H%x00%an%x00%ae%x00%cn%x00%ce%x00%B%x00')
    .split('\0').slice(0, -1);
  assert.equal(fields.length, 30 * 6, 'A full checkout with at least 30 commits is required.');
  for (let index = 0; index < fields.length; index += 6) {
    const [sha, authorName, authorEmail, committerName, committerEmail, message] = fields.slice(index, index + 6);
    const commit = {
      sha: sha.trim(), message,
      author: { name: authorName, email: authorEmail },
      committer: { name: committerName, email: committerEmail },
    };
    assert.deepEqual(inspectPullRequest({ commits: [commit] }).denied, [], commit.sha);
    t.diagnostic(`PASS commit ${commit.sha.slice(0, 7)} ${message.split('\n')[0]}`);
  }
});

test('merge subjects, local refs and preserved PR branches have the expected results', t => {
  const forbiddenPRs = new Set([32, 33, 34, 35, 36]);
  const history = git('log', '-30', '--format=%s').split('\n').flatMap(subject => {
    const match = /^Merge pull request #(\d+) from (\S+)/u.exec(subject);
    return match ? [{ number: Number(match[1]), branch: match[2] }] : [];
  });
  const refs = git('for-each-ref', '--format=%(refname)', 'refs/heads', 'refs/remotes')
    .trim().split('\n').filter(ref => !ref.endsWith('/HEAD'))
    .map(ref => {
      const branch = ref.replace(/^refs\/(heads\/|remotes\/[^/]+\/)/u, '');
      return { branch, number: branches.find(record => record.branch === branch)?.number };
    });
  const failedPRs = [];
  // The public PR API preserves branches missing from squash merges or deleted refs.
  for (const record of [...history, ...refs, ...branches]) {
    const denied = inspectPullRequest({ branch: record.branch }).denied.length > 0;
    assert.equal(denied, forbiddenPRs.has(record.number), record.branch);
    if (denied) failedPRs.push(record.number);
    t.diagnostic(`${denied ? 'FAIL (expected)' : 'PASS'} ${record.number ? `#${record.number} ` : ''}${record.branch}`);
  }
  assert.deepEqual([...new Set(failedPRs)].sort((a, b) => a - b), [...forbiddenPRs]);
});

test('synthetic prohibited branches, text and identities fail', t => {
  const cases = [
    ['vendor branch', { branch: 'codex/x' }],
    ['owner-prefixed branch', { branch: 'BichengWang/Claude-sdk' }],
    ['zero-width branch', { branch: 'co\u200Bdex/x' }],
    ['fullwidth branch', { branch: 'ｃｏｄｅｘ/x' }],
    ['bidi branch', { branch: 'co\u202Edex/x' }],
    ['generated body', { body: 'Generated with Codex' }],
    ['generated title', { title: 'Generated by Claude' }],
    ['zero-width body', { body: 'Generated with Co\u2060dex' }],
    ['fullwidth body', { body: 'Ｇｅｎｅｒａｔｅｄ ｗｉｔｈ Ｃｏｄｅｘ' }],
    ['coauthor trailer', { commits: [{ ...cleanCommit, message: 'Add checks\n\nCo-authored-by: Claude <noreply@example.com>' }] }],
    ['coauthor email', { commits: [{ ...cleanCommit, message: 'Co-authored-by: Helper <helper@openai.com>' }] }],
    ['author email', { commits: [{ ...cleanCommit, author: { ...identity, email: 'helper@anthropic.com' } }] }],
    ['committer name', { commits: [{ ...cleanCommit, committer: { ...identity, name: 'Codex' } }] }],
    ['fullwidth identity', { commits: [{ ...cleanCommit, author: { ...identity, name: 'Ｃｌａｕｄｅ' } }] }],
    ['zero-width email', { commits: [{ ...cleanCommit, committer: { ...identity, email: 'helper@op\u200Benai.com' } }] }],
  ];
  for (const [label, changes] of cases) {
    assert.ok(inspectPullRequest({ ...cleanPR, ...changes }).denied.length > 0, label);
    t.diagnostic(`FAIL (expected) ${label}`);
  }
});

test('normalization strips every specified control after NFKC', () => {
  const controls = [0x200B, 0x200C, 0x200D, 0x200E, 0x200F, 0x202A, 0x202B, 0x202C,
    0x202D, 0x202E, 0x2060, 0x2061, 0x2062, 0x2063, 0x2064, 0x2066, 0x2067, 0x2068, 0x2069, 0xFEFF];
  for (const codepoint of controls) {
    assert.equal(normalize(`Ｃｏ${String.fromCodePoint(codepoint)}ｄｅｘ`), 'Codex');
  }
});

test('normal area branches, KW identities and web-flow pass', () => {
  for (const branch of ['agents/eval-harness', 'agent/workflows', 'ci/attribution-guard', 'feature/router-workflow']) {
    for (const email of ['bichengwang17@gmail.com', '31808103+BichengWang@users.noreply.github.com']) {
      const commit = { ...cleanCommit, author: { ...identity, email }, committer: { name: 'GitHub', email: 'noreply@github.com' } };
      assert.deepEqual(inspectPullRequest({ ...cleanPR, branch, commits: [commit] }).denied, []);
    }
  }
});

test('text warnings annotate without denying ordinary vendor references', () => {
  const result = inspectPullRequest({ ...cleanPR, title: 'Update Claude SDK integration' });
  assert.deepEqual(result.denied, []);
  assert.equal(result.warnings[0].field, 'PR title');
});

function harness(commits = [cleanCommit], changes = {}) {
  const pr = {
    number: 44, head: { sha: cleanCommit.sha, ref: cleanPR.branch },
    user: { login: cleanPR.actor }, title: cleanPR.title, body: cleanPR.body,
    commits: commits.length, ...changes,
  };
  const calls = { rest: 0, graphql: 0, info: [], warning: [], error: [], failed: [] };
  const core = {
    info: message => calls.info.push(message), warning: message => calls.warning.push(message),
    error: message => calls.error.push(message), setFailed: message => calls.failed.push(message),
  };
  const context = { repo: { owner: 'BichengWang', repo: 'multi-agents' }, payload: { pull_request: structuredClone(pr) } };
  const github = {
    rest: { pulls: { get: async () => { calls.rest++; return { data: structuredClone(pr) }; } } },
    graphql: async (query, variables) => {
      calls.graphql++;
      const offset = Number(variables.cursor ?? 0);
      const next = offset + 100;
      return { repository: { pullRequest: {
        headRefOid: pr.head.sha,
        commits: {
          totalCount: commits.length,
          nodes: commits.slice(offset, next).map(commit => ({ commit: { ...commit, oid: commit.sha } })),
          pageInfo: { hasNextPage: next < commits.length, endCursor: String(next) },
        },
      } } };
    },
  };
  return { github, core, context, calls, pr };
}

test('the guard reads all pages and denies a prohibited 251st commit', async () => {
  const commits = Array.from({ length: 251 }, (_, index) => ({ ...cleanCommit, sha: index.toString(16).padStart(40, '0') }));
  commits[250].message = 'Co-authored-by: Codex <helper@example.com>';
  const h = harness(commits);
  await run(h);
  assert.equal(h.calls.graphql, 3);
  assert.equal(h.calls.rest, 2);
  assert.equal(h.calls.failed.length, 1);
  assert.match(h.calls.error[0], new RegExp(commits[250].sha));
});

test('the guard emits warnings and succeeds on a clean PR', async () => {
  const h = harness([cleanCommit], { title: 'Update Claude SDK integration' });
  await run(h);
  assert.equal(h.calls.warning.length, 1);
  assert.deepEqual(h.calls.failed, []);
  assert.match(h.calls.info.at(-1), /all 1 commits/u);
});

test('a dependabot PR passes using its API author, not the workflow actor', async () => {
  const h = harness([cleanCommit], { user: { login: 'dependabot[bot]' }, head: { sha: cleanCommit.sha, ref: 'dependabot/npm_and_yarn/openai-1' } });
  h.context.actor = 'BichengWang';
  await run(h);
  assert.deepEqual(h.calls.failed, []);
  assert.equal(h.calls.graphql, 0);
  const spoof = harness([cleanCommit], { head: { sha: cleanCommit.sha, ref: 'codex/x' } });
  spoof.context.actor = 'dependabot[bot]';
  await run(spoof);
  assert.equal(spoof.calls.failed.length, 1);
});

test('the guard fails closed on a changed head or an incomplete commit list', async () => {
  const changed = harness();
  changed.context.payload.pull_request.head.sha = 'b'.repeat(40);
  await assert.rejects(run(changed), /PR head changed/u);
  const incomplete = harness();
  const graphql = incomplete.github.graphql;
  incomplete.github.graphql = async (...args) => {
    const response = await graphql(...args);
    response.repository.pullRequest.commits.nodes = [];
    return response;
  };
  await assert.rejects(run(incomplete), /every PR commit/u);
});

test('the guard fails closed when metadata changes during verification', async () => {
  const h = harness();
  const get = h.github.rest.pulls.get;
  h.github.rest.pulls.get = async (...args) => {
    const response = await get(...args);
    if (h.calls.rest === 2) response.data.body = 'Generated with Codex';
    return response;
  };
  await assert.rejects(run(h), /PR changed during verification/u);
});
